bootstrap:
  image: localethereum/client-python
  container_name: bootstrap
  entrypoint: /usr/local/bin/pyethapp
  command: "-c eth.network_id=1337 -c node.privkey_hex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 -b 'enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@localhost:30303' run --fake"
  ports:
    - 127.0.0.1:30304:30303
    - 127.0.0.1:30304:30303/udp

eth:
  image: localethereum/client-python
  links: 
    - bootstrap
  entrypoint: /usr/local/bin/pyethapp
  command: "-c eth.network_id=1337 -b 'enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@bootstrap:30303' run --fake"

miner:
  image: localethereum/client-python
  links: 
    - bootstrap
  entrypoint: /usr/local/bin/pyethapp
  command: "-c eth.network_id=1337 -b 'enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@bootstrap:30303' -m 50 run --fake"

debug:
  image: localethereum/client-python
  container_name: debug
  links: 
    - bootstrap
  entrypoint: /usr/local/bin/pyethapp
  command: "-c eth.network_id=1337 -b 'enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@bootstrap:30303' -l :debug,p2p:info run --fake"
